-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/namespacemanager_namespace (
  nsm_id INTEGER UNSIGNED NOT NULL,
  nsm_name BLOB NOT NULL,
  nsm_talk_name BLOB DEFAULT NULL,
  nsm_content SMALLINT DEFAULT 0 NOT NULL,
  nsm_visual_editor SMALLINT DEFAULT 0 NOT NULL,
  nsm_search_default SMALLINT DEFAULT 0 NOT NULL,
  nsm_talk_search_default SMALLINT DEFAULT 0 NOT NULL,
  nsm_subpages SMALLINT DEFAULT 0 NOT NULL,
  nsm_talk_subpages SMALLINT DEFAULT 0 NOT NULL,
  nsm_includable SMALLINT DEFAULT 1 NOT NULL,
  nsm_talk_includable SMALLINT DEFAULT 1 NOT NULL,
  nsm_aliases BLOB NOT NULL,
  nsm_talk_aliases BLOB NOT NULL,
  nsm_edit_permissions BLOB NOT NULL,
  nsm_talk_edit_permissions BLOB NOT NULL,
  nsm_updated BLOB NOT NULL,
  PRIMARY KEY(nsm_id)
);

CREATE UNIQUE INDEX namespacemanager_namespace_name ON /*_*/namespacemanager_namespace (nsm_name);

CREATE UNIQUE INDEX namespacemanager_namespace_talk_name ON /*_*/namespacemanager_namespace (nsm_talk_name);
