-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/namespacemanager_namespace (
  nsm_id INT UNSIGNED NOT NULL,
  nsm_name VARBINARY(255) NOT NULL,
  nsm_talk_name VARBINARY(255) DEFAULT NULL,
  nsm_content TINYINT DEFAULT 0 NOT NULL,
  nsm_visual_editor TINYINT DEFAULT 0 NOT NULL,
  nsm_search_default TINYINT DEFAULT 0 NOT NULL,
  nsm_talk_search_default TINYINT DEFAULT 0 NOT NULL,
  nsm_subpages TINYINT DEFAULT 0 NOT NULL,
  nsm_talk_subpages TINYINT DEFAULT 0 NOT NULL,
  nsm_includable TINYINT DEFAULT 1 NOT NULL,
  nsm_talk_includable TINYINT DEFAULT 1 NOT NULL,
  nsm_aliases LONGBLOB NOT NULL,
  nsm_talk_aliases LONGBLOB NOT NULL,
  nsm_edit_permissions LONGBLOB NOT NULL,
  nsm_talk_edit_permissions LONGBLOB NOT NULL,
  nsm_updated BINARY(14) NOT NULL,
  UNIQUE INDEX namespacemanager_namespace_name (nsm_name),
  UNIQUE INDEX namespacemanager_namespace_talk_name (nsm_talk_name),
  PRIMARY KEY(nsm_id)
) /*$wgDBTableOptions*/;
